### ISSUE TITLE
Will not patch to Following Platinum v1.1.2?

### ISSUE THREAD

**Issue by y0miel** [TheGag96/individual-color-variation#10]
What it says on the tin. I've been trying to find a v1.1.1 patch of Following Platinum instead but can't find anything besides the latest version. Am I missing something or should I just give up on this?

**Comment by TheGag96** [comment]
Is there something wrong with Following Platinum's latest version?

**Comment by y0miel** [comment]
Possibly? I try to patch it onto a Individual Color patched rom and just get an error. Am I doing something wrong? Thanks for taking the time to reply!

**Comment by TheGag96** [comment]
Ah wait, I see - I didn't even realize that Following Platinum had an update like a year and a half ago... I'll have to update the patches.

**Comment by TheGag96** [comment]
@y0miel Sorry I took so long with this!! Check the updated release and close this issue if it works for you.
