### ISSUE TITLE
Fallocate not found

### ISSUE THREAD

**Issue by RottingCrow** [TheGag96/individual-color-variation#12]
I'm trying to build the files manually following the tutorial in the read me however when trying to build the files via Msys2 I get the error "fallocate: command not found"

Am I using the wrong program/terminal to build the files or is there something else I need to install for this to work?

Edit in case it matters: I'm trying to patch HeartGold using the dedicated branch

**Comment by TheGag96** [comment]
I actually was bitten by this myself when I switched from Linux to Windows... It's a utility that isn't included with MSYS2/MinGW. I probably need to switch this to something else. If you can just make a blank file the size of what I'm trying to make externally (HxD is one such option) and commenting out the build script lines that call fallocate and delete the file, you'll be able to hobble along. Sorry about that!!

**Comment by RottingCrow** [comment]
Thank you, especially for your fast response! I think I got that part to work? I made a file with 32768 (32x1024) bytes named tmp_custom_overlay and commented out the fallocate line. I'm now getting an error from the PokeEditor lines. It throws a warning saying 'taskbar.setIconImage' isn't supported then opens PokeEditor. Closing PokeEditor creates an error from the line moving the temp file. I'm unsure if I'm supposed to do something with the editor or if another line isn't working properly with my setup.

**Comment by TheGag96** [comment]
Can you post the error? Are you using PokEditor v1?

**Comment by RottingCrow** [comment]
![PXL_20240507_190105940~2](https://github.com/TheGag96/individual-color-variation/assets/109051364/cf3a698f-4019-4cd1-8035-86e6bd518ef4)
Tried attaching a picture of the error. I have PokeEditor v 3.1.1 right now. Do I need to downgrade for this to work?

**Comment by TheGag96** [comment]
Yeah, you gotta use v1 to use it on the command line like I'm doing. It would be nice to have a narc library built into this repo that would make that unnecessary...

**Comment by RottingCrow** [comment]
Thank you! I've gotten everything to work!
