### ISSUE TITLE
Double batle problem 

### ISSUE THREAD

**Issue by Eremenk** [TheGag96/individual-color-variation#6]
On an actual ds double battle, in following renegade platinum, show a black screen with sound on background.
With ds emulator it works normal, without errors.

**Comment by TheGag96** [comment]
Crap... You are not the first person who's reported this. Apparently melonDS emulates the console well enough to have this crash there also. That's absolutely strange. I have no idea why that would occur.

**Comment by SubliminalSiren** [comment]
Also having this issue, the first double battle causes a black screen on following renegade platinum. (Twilight Menu 3DS)

**Comment by TheGag96** [comment]
Have you guys seen this error on any other version than Following Renegade, like Following Plat or Vanilla Plat?

**Comment by TheGag96** [comment]
Okay so it crashes on all of them... Arghh. It's hard to debug because it doesn't happen in the only emulator with a debugger.

**Comment by TheGag96** [comment]
@Eremenk @SubliminalSiren Sorry for the delay on fixing this. Please try the new patches!

**Comment by SubliminalSiren** [comment]
Will do, thanks for getting this sorted, excited to play it again!

**Comment by Eremenk** [comment]
Now game crach by using tackle

**Comment by TheGag96** [comment]
@SubliminalSiren @Eremenk Please redownload the Following / Following Renegade patches. I messed them up. Really sorry about that!!
