### ISSUE TITLE
Patch 

### ISSUE THREAD

**Issue by Eremenk** [TheGag96/individual-color-variation#7]
problems with patching following renegade platinum. it gives an error all the time (a couple of months ago everything seemed to be fine)

**Comment by TheGag96** [comment]
Did you start with a clean ROM, patching Renegade Platinum by itself without any other patches, then patching my stuff on top of that?

**Comment by Eremenk** [comment]
yes. I patched both the usual platinum with the renegade patch and the following and platinum renegade with the following patch. in both cases, the unique colors patch did not want to be installed on patched roms, giving an error (this rom is not compatible with the patch)

**Comment by TheGag96** [comment]
Ah... It looks as though there was an update to Following Renegade in August that I didn't catch. I'll have to go and update the patch. Thanks for letting me know!

**Comment by TheGag96** [comment]
@Eremenk just whipped a patch up. Would you mind giving it a test? Thanks!!

**Comment by Eremenk** [comment]
everything works perfectly. Thanks
